### ISSUE TITLE
Error numpy

### ISSUE THREAD

**Issue by walterm128** [cosmonium/cosmonium#21]
Using C++ Engine
Traceback (most recent call last):
  File "__main__", line 38, in <module>
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "cosmonium.cosmonium", line 54, in <module>
  File "importlib._bootstrap", line 1035, in _handle_fromlist
  File "importlib._bootstrap", line 219, in _call_with_frames_removed
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "cosmonium.parsers.parsers", line 26, in <module>
  File "importlib._bootstrap", line 1035, in _handle_fromlist
  File "importlib._bootstrap", line 219, in _call_with_frames_removed
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "cosmonium.parsers.bodiesparser", line 34, in <module>
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "cosmonium.parsers.surfacesparser", line 27, in <module>
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "cosmonium.heightmap", line 31, in <module>
  File "importlib._bootstrap", line 983, in _find_and_load
  File "importlib._bootstrap", line 967, in _find_and_load_unlocked
  File "importlib._bootstrap", line 677, in _load_unlocked
  File "importlib._bootstrap", line 819, in exec_module
  File "numpy", line 305, in <module>
  File "numpy", line 302, in _win_os_check
RuntimeError: The current Numpy installation ('D:\\Utiles\\_InvestigacionCientifica\\Astronomia\\cosmonium\\cosmonium.exe') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

Windows 10 20H2

**Comment by el-dee** [comment]
Great, a regression introduced by Windows update 10.0.19041.488 and the fix is not scheduled before end of January 2021 !

Thank you for reporting this, I will try and downgrade numpy version to 1.19.3 for the time being

**Comment by el-dee** [comment]
The workaround seems to work, no more crashes with Windows 10 20H2, the bugfix release V0.2.1.1 is available on the [download ](https://github.com/cosmonium/cosmonium/wiki/Download) page.
