### ISSUE TITLE
Rock Demo Render Problems

### ISSUE THREAD

**Issue by Gladius1** [cosmonium/cosmonium#25]
![Rock Demo](https://user-images.githubusercontent.com/7734361/112309965-4f6cfd00-8ca4-11eb-87f0-9d59f5714e83.jpg)
I'm interested in the procedural generated planets. Planet Demo is pretty impressive but has some performance issues. The Gas Demo planet crashes the game unfortunately and the Rock Demo looks extremely spiky, like with 400000 km long spikes. 

System: ubuntu mate 20.04
CPU: Core i5 6200 U
GPU: Nvidia 940MX with Nvidia drivers
I built Cosmonium and panda3d without errors and all the other Planets look OK.

Apart from that, very impressive, but could use some more comments in the code.

**Comment by el-dee** [comment]
Thank you for your feedback !

The "Rock demo" bug is now fixed, the terrain shader was not properly cleared when moving from one planet to another and so it was still using the scale factor of the "planet demo" object. I will push the fix once Panda3D 1.10.9 is out as it relies on improvements found in it.

I don't get any crash with the "Gas demo". If you still have it, could you attach the log file  ~/.local/share/cosmonium/output.log ?

Improving the performance and cleaning up the code (and indeed add some really needed comments...) is my top priority right now. 
I have simplified the quadtree and I'm working on caching the terrain surface textures to lower the work load on the GPU every frames.Next step will be to port the quadtree code to C++ as it is the last major performance bottleneck.

**Comment by Gladius1** [comment]
Thanks for fixing the bug.
This is the error I get when I zoom in on Gas Demo.
```

Select Gas Demo
Go to Gas Demo
Follow Gas Demo
New nearest object: Planet Demo
New nearest object: Gas Demo
Visible bodies 1 : Gas Demo
Create light for Gas Demo
Creating shader basic-u-rs-sss-lambert-mur (39c7095561be1bd71146769e29468eb7)
Traceback (most recent call last):
  File "~/cosmonium/cosmonium/cosmonium.py", line 1096, in time_task
    self.update_instances()
  File "~/cosmonium/cosmonium/pstats.py", line 34, in doPstat
    returned = func(*args, **kargs)
  File "~/cosmonium/cosmonium/cosmonium.py", line 1009, in update_instances
    self.universe.check_and_update_instance(self.observer.get_camera_pos(), self.observer.get_camera_rot(), self.pointset)
  File "~/cosmonium/cosmonium/universe.py", line 183, in check_and_update_instance
    leaf.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/systems.py", line 231, in check_and_update_instance
    child.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/stellarobject.py", line 558, in check_and_update_instance
    CompositeObject.check_and_update_instance(self, camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/foundation.py", line 333, in check_and_update_instance
    component.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/foundation.py", line 250, in check_and_update_instance
    self.update_instance(camera_pos, camera_rot)
  File "~/cosmonium/cosmonium/shapes.py", line 448, in update_instance
    self.shader.update(self.shape, self.appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 99, in update
    self.update_shader_shape(shape, appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 1187, in update_shader_shape
    shadow.update_shader_shape(shape, appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 2471, in update_shader_shape
    (texture, texture_size, texture_lod) = ring.appearance.texture.source.get_texture(ring.shape)
  File "~/cosmonium/cosmonium/procedural/textures.py", line 140, in get_texture
    while parent_patch is not None and parent_patch.str_id() not in self.map_patch:
AttributeError: 'Ring' object has no attribute 'str_id'
:task(error): Exception occurred in PythonTask time-task
Traceback (most recent call last):
  File "~/cosmonium/main.py", line 296, in <module>
    app.run()
  File "~/cosmonium/venv/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3318, in run
    self.taskMgr.run()
  File "~/cosmonium/venv/lib/python3.8/site-packages/direct/task/Task.py", line 539, in run
    self.step()
  File "~/cosmonium/venv/lib/python3.8/site-packages/direct/task/Task.py", line 493, in step
    self.mgr.poll()
  File "~/cosmonium/cosmonium/cosmonium.py", line 1096, in time_task
    self.update_instances()
  File "~/cosmonium/cosmonium/pstats.py", line 34, in doPstat
    returned = func(*args, **kargs)
  File "~/cosmonium/cosmonium/cosmonium.py", line 1009, in update_instances
    self.universe.check_and_update_instance(self.observer.get_camera_pos(), self.observer.get_camera_rot(), self.pointset)
  File "~/cosmonium/cosmonium/universe.py", line 183, in check_and_update_instance
    leaf.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/systems.py", line 231, in check_and_update_instance
    child.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/stellarobject.py", line 558, in check_and_update_instance
    CompositeObject.check_and_update_instance(self, camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/foundation.py", line 333, in check_and_update_instance
    component.check_and_update_instance(camera_pos, camera_rot, pointset)
  File "~/cosmonium/cosmonium/foundation.py", line 250, in check_and_update_instance
    self.update_instance(camera_pos, camera_rot)
  File "~/cosmonium/cosmonium/shapes.py", line 448, in update_instance
    self.shader.update(self.shape, self.appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 99, in update
    self.update_shader_shape(shape, appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 1187, in update_shader_shape
    shadow.update_shader_shape(shape, appearance)
  File "~/cosmonium/cosmonium/shaders.py", line 2471, in update_shader_shape
    (texture, texture_size, texture_lod) = ring.appearance.texture.source.get_texture(ring.shape)
  File "~/cosmonium/cosmonium/procedural/textures.py", line 140, in get_texture
    while parent_patch is not None and parent_patch.str_id() not in self.map_patch:
AttributeError: 'Ring' object has no attribute 'str_id'
```

**Comment by el-dee** [comment]
Thanks, it is fixed in the latest develop with the overhaul of the procedural appearance. I will probably release a dev build next week or so with a bunch of other performance improvements, if they are stable enough :)
